name:                lazyboy
version:             0.2.0.1
github:              "ix/lazyboy"
license:             BSD3
author:              "Rose"
maintainer:          "rose@lain.org.uk"
copyright:           "2019 Rose"
category:            DSL, Compiler
synopsis:            An EDSL for programming the Game Boy.

extra-source-files:
- README.md
- ChangeLog.md

# templates
data-files: templates/*.mustache

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: An EDSL for programming the Nintendo Game Boy. <https://github.com/ix/lazyboy#readme>

dependencies:
 - aeson >= 1.4.2.0 && < 1.5
 - base >= 4.7 && < 5
 - hspec >= 2.6.1 && < 2.7
 - microstache >= 1.0.1.1 && < 1.1
 - text >= 1.2.3.1 && < 1.3
 - transformers >= 0.5.6.2 && < 0.6

library:
  source-dirs: src

#executables:
#  lazyboy:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - lazyboy
#
tests:
  lazyboy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lazyboy 


ghc-options: ["-optP-Wno-nonportable-include-path"]
