name:                lazyboy
version:             0.1.0.0
github:              "ix/lazyboy"
license:             BSD3
author:              "Rose"
maintainer:          "rose@lain.org.uk"
copyright:           "2018 Rose"

extra-source-files:
- README.md
- ChangeLog.md

# templates
data-files: templates/*.mustache

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         An EDSL for programming the Nintendo Game Boy. <https://github.com/ix/lazyboy#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- microstache 
- aeson
- text

library:
  source-dirs: src

executables:
  lazyboy:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lazyboy

tests:
  lazyboy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lazyboy 
